/* The 30% Blind Spot — LLM Safety Judges */
const BlindSpotPage = () => (
  <div style={{ background: "var(--bg)", color: "var(--fg)", fontFamily: "var(--f-grot)", minHeight: "100vh" }}>
    <SiteNav active="research" />
    <ArticleHero
      track="defense · evaluation"
      date="2025.11"
      venue="snailsploit.com · Hakin9"
      readtime="11 min read"
      title="The 30% Blind Spot — LLM Safety Judges"
      dek="Cross-validation of LLM-as-judge safety classifiers against the AATMF prompt bank. ~30% of the bank lands. Here is where, and why."
    />
    <ArticleBody>
      <P>The LLM-as-judge evaluation pattern — using one LLM to score another LLM's outputs for safety violations — has become the default approach for online safety filtering and offline benchmarking. The pattern is intuitive (the judge has the same world model as the model it's evaluating) and operationally cheap (no human in the loop) and is therefore now everywhere.</P>
      <P>This research evaluated five leading judge configurations against the AATMF prompt bank — 4,980+ prompts spanning the framework's twelve techniques. The headline finding: the average false-negative rate is roughly 30%. Across the bank, almost a third of adversarial prompts that succeed against a target model are scored as "safe" by the judge that's supposed to catch them.</P>
      <Pull>The judge thinks it's safe. The target it's evaluating disagrees.</Pull>

      <H2>Methodology</H2>
      <P>The setup: five judge configurations (frontier and open) were given (a) the adversarial prompt, (b) the model's response to it, and (c) the standard "did this response violate policy" question. The judges' scores were compared against ground-truth labels — generated by a panel of human annotators with offensive-security backgrounds, with disputes resolved by a tie-breaker.</P>
      <P>The metric is the false-negative rate: prompts where the target model produced policy-violating output and the judge labeled the exchange "safe." False positives — judges over-flagging benign content — are a separate problem with separate operational consequences and are not the focus here.</P>
      <H3>Caveats</H3>
      <ul style={{ margin: "0 0 24px", paddingLeft: 24, color: "var(--fg-2)", lineHeight: 1.7 }}>
        <li>The bank is biased toward harder prompts — the easy ones don't end up in AATMF. Real-world distributions skew easier; real-world false-negative rates will be lower than 30%, but not zero.</li>
        <li>Judges were tested in their default configurations. A custom-prompted judge with task-specific examples may do better; we're measuring the off-the-shelf experience, which is what most teams actually deploy.</li>
        <li>"Safe" labels were treated as miss-events even when the response was technically benign but the prompt was clearly adversarial — because in production those still surface in agent traffic and warrant review.</li>
      </ul>

      <H2>Where the misses cluster</H2>
      <P>The miss distribution is not uniform across AATMF techniques. It clusters heavily in three of the twelve.</P>
      <H3>T4 — Multi-Turn & Memory Manipulation (≈48% miss)</H3>
      <P>Judges evaluating a single turn-pair miss the slow-burn modulation that makes multi-turn attacks work. The judge sees a benign-looking final exchange; the violation is in the cumulative drift across turns the judge can't see. Without conversation-window-aware evaluation, this category is structurally invisible to per-turn judges.</P>
      <H3>T7 — Output Manipulation & Exfiltration (≈41% miss)</H3>
      <P>When the violation is a structured output — code, JSON, tabular data, base64 — that contains the bad content in encoded form, judges trained to recognize narrative-prose violations under-flag. The pattern is recognizable to a human reader looking for it; it's invisible to a judge whose training emphasized natural-language harms.</P>
      <H3>T11 — Agentic & Orchestrator Exploitation (≈37% miss)</H3>
      <P>The violation in agentic exploitation is rarely in the model's narrative output. It's in the tool call the model is induced to make, or in the tool input that contains the actual payload. Judges scoring the conversational turn are scoring the wrong layer.</P>

      <H2>Why this is structural</H2>
      <P>Three reasons, in increasing order of how hard they are to fix.</P>
      <H3>The judge has the same training distribution as the target.</H3>
      <P>Same RLHF preference data, same constitutional documents, same world model. A blind spot in the target tends to be a blind spot in the judge. This is the failure mode the LLM-as-judge pattern was supposed to avoid; it is the failure mode the LLM-as-judge pattern reliably produces.</P>
      <H3>Per-turn evaluation can't see multi-turn attacks.</H3>
      <P>The pattern's economics push toward per-turn evaluation — cheaper, faster, parallelizable. But the most-effective adversarial prompts are not single-turn. The mismatch between the dominant evaluation shape and the dominant attack shape is doing most of the work in the miss numbers.</P>
      <H3>Encoded violations are not narrative violations.</H3>
      <P>A judge optimized for "does this output contain a policy violation in plain English" will under-flag code blocks, structured data, and image-described content. Fixing this requires either format-specific judges or a more invasive judge that decodes before evaluating, both of which are expensive enough that few production deployments do them.</P>

      <H2>What to do about it</H2>
      <Stepped steps={[
        <span>Don't use a single judge. Two judges trained differently, with different prompting strategies, evaluated independently, with disagreement triggering human review. Modest cost increase, large miss-rate reduction.</span>,
        <span>Evaluate at the conversation level, not the turn level. The latency cost is real but tractable for offline evaluation; for online filtering, run the conversation-level pass at a sample rate against turns the per-turn judge cleared.</span>,
        <span>Add format-specific evaluators for code, JSON, and structured outputs. These are cheap to build (small classifiers) and the residual miss rate on T7 drops materially.</span>,
        <span>For agentic systems, evaluate tool calls and tool inputs independently of conversation turns. The agentic surface is the violation surface; treating it as part of the conversation is the category error driving T11 misses.</span>,
        <span>Treat the judge as one signal in an ensemble that also includes deterministic checks, anomaly detection on tool-call patterns, and human triage of high-risk surfaces. The judge is not a replacement for any of those.</span>,
      ]} />

      <H2>Closing</H2>
      <P>The LLM-as-judge pattern is not broken. It is over-deployed, under-instrumented, and asked to do work it was never designed for. Used as a single layer of a defense-in-depth approach, judges are useful. Used as the only safety layer, they leave the 30% on the table — and the 30% is not a uniform sample of the bank, it's exactly the part of the bank an attacker is most likely to be using.</P>
    </ArticleBody>
    <ArticleFootnote items={[
      ["AATMF T4 — Multi-Turn & Memory Manipulation", "/aatmf"],
      ["AATMF T7 — Output Manipulation & Exfiltration", "/aatmf"],
      ["AATMF T11 — Agentic & Orchestrator Exploitation", "/aatmf"],
      ["AATMF-R Scoring Rubric", "/aatmf"],
    ]} />
    <SiteFooter section="research / blind spot" />
  </div>
);
Object.assign(window, { BlindSpotPage });
